# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd6fb994f48c7c18eb6dec822b8cf4949b341de3b7d3db066550c40b8a52105b578d991323d83aede565ab025861461cd0b5697bc89aed2b4bf27c4160033660

test:
  secret_key_base: c958b8ebf48063156e57be2f07498f124b8abc92d4441140cfdc52519ccc6e98fee620c67045c2853e6ef887e7e8461158e4be77d889a860bd58900d16fcfeb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
